9
kenta-yamazaki/java_lesson pull request #10
Opened 2019-05-10 04:34 UTC by kenta-yamazaki

2019-05-10 04:36 UTC, kenta-yamazaki commented
@shunji-yamaguchi
@hironoriohashi
9章のプログラム作成しました。レビューお願いいたします！

2019-05-10 08:05 UTC, hironoriohashi commented on src/sho9/ShowMaxData.java
> +        int maxData = data[0];
変数名`maxData`の`Data`から得られる情報が無いため、
この場合の変数名は`maxNumber`や単に`max`といった変数名が望ましいと思います。

2019-05-10 08:07 UTC, hironoriohashi commented on src/sho9/SelectGreeting.java
> +            System.out.println("番号は0〜" + (message.length - 1) + "び範囲で指定してください。");
`び範囲`
誤字？

2019-05-10 08:46 UTC, kenta-yamazaki commented on src/sho9/SelectGreeting.java
> +            System.out.println("番号は0〜" + (message.length - 1) + "び範囲で指定してください。");
@hironoriohashi
すみません、誤字です。修正しました。

2019-05-10 08:47 UTC, kenta-yamazaki commented on src/sho9/ShowMaxData.java
> +        int maxData = data[0];
@hironoriohashi
変数名を変更しました。

2019-05-10 08:48 UTC, kenta-yamazaki commented
@shunji-yamaguchi
@hironoriohashi 
修正しました。再度レビューお願いします！

2019-05-10 10:48 UTC, hironoriohashi approved these changes
良いと思います

2019-05-13 01:43 UTC, shunji-yamaguchi requested changes
@kenta-yamazaki 
レビューしました。ご確認をよろしくお願いします。

2019-05-13 01:43 UTC, shunji-yamaguchi commented on src/sho9/Heikin6.java
> +                {100, 100, 100, 100}
@kenta-yamazaki 
教本のサンプルコードと比べて、3要素目の配列の要素数が少ないですね。
サンプルコードのように要素ごとの縦列をそろえると、可読性が増しますし要素数の過不足も気づきやすくなりますよ。

2019-05-13 01:43 UTC, shunji-yamaguchi commented on src/sho9/Kamoku.java
> +    int kamokuTensu;    //点数
@kenta-yamazaki 
`kamokuName`は科目を表すクラス `Kamoku` が持つフィールドですね。
なのでフィールド名は `name` だけでも科目の名前であることは伝わると思いました。
`kamokuTensu` についても同様です。
修正するかはお任せします 🙏

2019-05-13 01:43 UTC, shunji-yamaguchi commented on src/sho9/sortData.java
> +public class sortData {
@kenta-yamazaki 
クラス名が小文字はじまりになっていますね。

2019-05-15 00:12 UTC, kenta-yamazaki commented on src/sho9/Heikin6.java
> +                {100, 100, 100, 100}
@shunji-yamaguchi
要素を追加し、縦列を揃えました。

2019-05-15 00:13 UTC, kenta-yamazaki commented
@shunji-yamaguchi 
@hironoriohashi 
修正しました。再度レビューお願いします。

2019-05-15 00:14 UTC, kenta-yamazaki commented on src/sho9/sortData.java
> +public class sortData {
@shunji-yamaguchi
修正しました。

2019-05-15 00:15 UTC, shunji-yamaguchi approved these changes
@kenta-yamazaki 
🆗 です。

2019-05-15 00:16 UTC, kenta-yamazaki commented
@shunji-yamaguchi 
@hironoriohashi 
ありがとうございます！

2019-05-15 00:16 UTC, merged