10章
kenta-yamazaki/java_lesson pull request #11
Opened 2019-05-10 08:04 UTC by kenta-yamazaki

@shunji-yamaguchi
@hironoriohashi
10章のプログラム作成しました。
レビューお願い致します！！

2019-05-10 11:09 UTC, hironoriohashi reviewed
問題10-3は行わないのですか？

2019-05-13 00:41 UTC, kenta-yamazaki commented
@shunji-yamaguchi
@hironoriohashi 
問題10-3を追加しました。再度レビューお願いします！

2019-05-13 02:39 UTC, shunji-yamaguchi requested changes
@kenta-yamazaki 
レビューしました。ご確認をよろしくお願いします。

2019-05-13 02:39 UTC, shunji-yamaguchi commented on src/sho10/Kamoku.java
> +        return this.kamokuName + "は" + kamokuScore + "点";
@kenta-yamazaki 
これでも問題ありませんがどちらもフィールドなので、thisをつけるかつけないのどちらかに統一したほうが良いかなと思いました。

2019-05-13 02:39 UTC, shunji-yamaguchi commented on src/sho10/ProductItem.java
> +    int price;  //価格
@kenta-yamazaki 
こちらのコメントもJavaDoc形式に修正してみてください。

2019-05-13 02:39 UTC, shunji-yamaguchi commented on src/sho10/Rectangle.java
> +    int height;    //長方形の高さ
@kenta-yamazaki 
こちらのコメントもJavaDoc形式に修正してみてください。

2019-05-13 02:39 UTC, shunji-yamaguchi commented on src/sho10/Student.java
> +    int[] testScores;   //試験の点数
@kenta-yamazaki
こちらのコメントもJavaDoc形式に修正してみてください。

2019-05-13 02:39 UTC, shunji-yamaguchi commented on src/sho10/Kamoku.java
> +    int kamokuScore;    //点数
@kenta-yamazaki
フィールドのコメントもJavaDoc形式でドキュメンテーションコメントとして記述しておきましょうか。
/** */の形式でフィールド宣言の上に記述すれば良いです。

2019-05-13 02:39 UTC, shunji-yamaguchi commented on src/sho10/Kamoku.java
> +    //コンストラクタ
@kenta-yamazaki 
こちらのコメントもJavaDoc形式に修正してみてください。

2019-05-13 02:39 UTC, shunji-yamaguchi commented on src/sho10/Kamoku.java
> +    //科目の文字列表現
こちらのコメントもJavaDoc形式に修正してみてください。

2019-05-13 04:24 UTC, kenta-yamazaki commented on src/sho10/Kamoku.java
> +    int kamokuScore;    //点数
@shunji-yamaguchi
    /**
     * 科目名、科目の点数を表します
     */
    String kamokuName;
    int kamokuScore;
という直し方で合っていますか？

2019-05-13 05:16 UTC, shunji-yamaguchi commented on src/sho10/Kamoku.java
> +    int kamokuScore;    //点数
@kenta-yamazaki 

いえ、フィールドのドキュメンテーションコメントはフィールドごとに１つずつ書いてください。

たとえば以下が`System.out.println`で使用しているSystemクラスのJavaDocリファレンスです。
https://docs.oracle.com/javase/jp/8/docs/api/java/lang/System.html
**フィールドとサマリー**の項目にフィールドとその説明が書いてあります。
フィールドに記述したドキュメンテーションコメントはJavaDocで出力するとこのように表示されます。

実際の`System`クラスのコメントと比較すると書き方がよりわかるかなと思います。
IntelJだとソースコードの`System`にカーソルを持ってきて`F4`を押せば、`System`クラスのソースに飛べるはずなので試してみてください。

2019-05-13 07:12 UTC, kenta-yamazaki commented on src/sho10/Kamoku.java
> +        return this.kamokuName + "は" + kamokuScore + "点";
@shunji-yamaguchi
thisに統一しました

2019-05-13 07:13 UTC, kenta-yamazaki commented on src/sho10/ProductItem.java
> +    int price;  //価格
@shunji-yamaguchi
JavaDoc形式に修正しました。

2019-05-13 07:13 UTC, kenta-yamazaki commented on src/sho10/Rectangle.java
> +    int height;    //長方形の高さ
@shunji-yamaguchi
JavaDoc形式に修正しました。

2019-05-13 07:13 UTC, kenta-yamazaki commented on src/sho10/Kamoku.java
> +    int kamokuScore;    //点数
@shunji-yamaguchi
ありがとうございます！
JavaDoc形式に修正しました。

2019-05-13 07:14 UTC, kenta-yamazaki commented on src/sho10/Kamoku.java
> +    //コンストラクタ
@shunji-yamaguchi
JavaDoc形式に修正しました。

2019-05-13 07:14 UTC, kenta-yamazaki commented on src/sho10/Kamoku.java
> +    //科目の文字列表現
@shunji-yamaguchi
JavaDoc形式に修正しました。

2019-05-13 07:14 UTC, kenta-yamazaki commented
@shunji-yamaguchi 
@hironoriohashi 
修正しました。再度レビューお願いします！

2019-05-13 07:53 UTC, shunji-yamaguchi requested changes
@kenta-yamazaki 
レビューしました。ご確認をよろしくお願いします。

2019-05-13 07:53 UTC, shunji-yamaguchi commented on src/sho10/Kamoku.java
> +     * @return 戻り値
@kenta-yamazaki 
戻り値についてのコメントが`戻り値`では何も伝わりませんね（戻り値のコメントであることは`@return`タグより分かるので）

また、メソッドのコメント`科目の文字列表現`についても、よいコメントとは言えません。
メソッドはオブジェクトの操作を行うものですが、このコメントからは何をするメソッドなのか伝わらないので。
動詞を使用して文章の形で記述するのが良いです。

修正してみてください。

2019-05-13 08:35 UTC, kenta-yamazaki commented on src/sho10/Kamoku.java
> +     * @return 戻り値
@shunji-yamaguchi
修正しました。

2019-05-13 08:36 UTC, kenta-yamazaki commented
@shunji-yamaguchi 
@hironoriohashi 
修正しました。再度レビューお願いします。

2019-05-13 09:19 UTC, shunji-yamaguchi requested changes
@kenta-yamazaki 
レビューしました。ご確認をよろしくお願いします。

2019-05-13 09:19 UTC, shunji-yamaguchi commented on src/sho10/Kamoku.java
> +     * @return 科目と科目点数を反映させた文字列
@kenta-yamazaki 

> 科目の文字列を出力

`出力`だとコンソールに標準出力するメソッドだと読み取られそうですね。
このメソッドはあくまで返り値で返すメソッドなので`○○を返す。`というコメントが良いかなと思います。
そして`○○`に相当する文章は、`@return`のコメントがそのまま使用できそうです。

また、メソッドの説明は体言止めでなく用語止めで書いておくのが良いと思います。
今回は簡単なメソッドなので書けていますが、メソッドの説明を詳しく複数行で書こうとすると、必然的に体言止めだと表現できなくなると思うので。

> 科目と科目点数を反映させた文字列

個人的に`反映`だとなにか反映する明確な対象があるように感じるので、`○○を○○に反映させた`と書きたくなります。
修正前の`表現`という言葉のほうが良いかなと思いました。

2019-05-14 00:25 UTC, kenta-yamazaki commented on src/sho10/Kamoku.java
> +     * @return 科目と科目点数を反映させた文字列
@shunji-yamaguchi
ありがとうございます！修正致しました。

2019-05-14 00:26 UTC, kenta-yamazaki commented
@shunji-yamaguchi 
@hironoriohashi 
修正しました。再度レビューお願いします！！

2019-05-14 02:12 UTC, shunji-yamaguchi requested changes
@kenta-yamazaki 
レビューしました。ご確認をよろしくお願いします。

2019-05-14 02:12 UTC, shunji-yamaguchi commented on src/sho10/Kamoku.java
> +     * @return 科目の文字列を返す
@kenta-yamazaki 

まだ修正してほしい部分があります 🙏 

> 科目の文字列を表現する

ここはメソッドの動作の説明を書くべき部分ですね。
このコメントだと何をするメソッドなのか伝わりきらないと思います。
`○○を返す。`の形で書いてみてください。

> 科目の文字列を返す

`@return`タグは戻り値に関する説明を書くためのタグなので、`返す`は不要です。
また`科目の文字列`では、String型の`科目`だととらえられそうです。
こちらにも`表現`という言葉が必要そうです。

参考に以下がJava標準APIのObjectクラスのtoStringメソッドのJavaDocです。（Objectクラスについては１２章で学ぶ内容です。）
https://docs.oracle.com/javase/jp/8/docs/api/java/lang/Object.html#toString--
このようにJavaDocだと、通常のコメントは`オブジェクトの文字列表現を返します。一般に～`のような形で出力され、`@return`タグで記述したコメントは**戻り値**の欄に出力されます。

2019-05-14 02:31 UTC, kenta-yamazaki commented on src/sho10/Kamoku.java
> +     * @return 科目の文字列を返す
@shunji-yamaguchi
何度も申し訳ありません🙇🏻‍♂️
メソッドの説明には、`オブジェクトの文字列表現を返します`
戻り値には、`このオブジェクトの文字列表現`
でよろしいでしょうか？

2019-05-14 02:45 UTC, shunji-yamaguchi commented on src/sho10/Kamoku.java
> +     * @return 科目の文字列を返す
@kenta-yamazaki 
良いです、ですがせっかくなので以前のコミットで書いてもらっていた`科目と科目点数を反映させた文字列`を修正する形にしたいなと思っています。
戻り値が、`科目名と点数を表現する文字列`
メソッドの説明が、`科目名と点数を表現する文字列を返します。`
とかですね。

2019-05-14 02:52 UTC, kenta-yamazaki commented on src/sho10/Kamoku.java
> +     * @return 科目の文字列を返す
@shunji-yamaguchi
なるほど、`表現する文字列`という書き方ができるんですね！
理解できた気がします。ありがとうございます！

2019-05-14 02:58 UTC, kenta-yamazaki commented on src/sho10/Kamoku.java
> +     * @return 科目の文字列を返す
@shunji-yamaguchi
修正しました。

2019-05-14 02:59 UTC, kenta-yamazaki commented
@shunji-yamaguchi 
@hironoriohashi 
修正しました。再度レビューお願いします！

2019-05-14 04:28 UTC, shunji-yamaguchi approved these changes
@kenta-yamazaki 
🆗 です 👍

2019-05-14 10:18 UTC, hironoriohashi approved these changes
良いと思います

2019-05-15 00:17 UTC, kenta-yamazaki commented
@shunji-yamaguchi 
@hironoriohashi 
ありがとうございます！

2019-05-15 00:17 UTC, merged