11章
kenta-yamazaki/java_lesson pull request #12
Opened 2019-05-15 03:01 UTC by kenta-yamazaki

@shunji-yamaguchi
@hironoriohashi
第11章のプログラム作成しました。
RectangleTest.javaはRectangleクラスを実行するファイルなのでよかったら使ってください。
レビューお願いします！

2019-05-15 03:44 UTC, hironoriohashi commented on src/sho11/Rectangle21.java
> +            return true;
nullチェックの後の処理を1行で記述できそうです。
1行で記述できるように変更してみてください。

2019-05-15 06:32 UTC, shunji-yamaguchi requested changes
@kenta-yamazaki 
レビューしました。ご確認をよろしくお願いします。

2019-05-15 06:32 UTC, shunji-yamaguchi commented on src/sho11/Rectangle23.java
> +        this.height = height;
@kenta-yamazaki 
教本の範囲外なのですが、[三項演算子](https://www.javadrive.jp/start/ope/index13.html)を使用すると処理がシンプルに記述できます。

2019-05-15 06:32 UTC, shunji-yamaguchi commented on src/sho11/Rectangle24.java
> +        int ey = Math.min(this.y + this.height, rectangle.y + rectangle.height);
@kenta-yamazaki 
この変数名だと変数がなにを示しているか分かりにくいですね。
修正してみてください。

2019-05-15 06:32 UTC, shunji-yamaguchi commented on src/sho11/RectangleTest.java
> +        System.out.println("長方形の面積は、"+r.getArea()+"㎠です。");
@kenta-yamazaki 
なにか文字化けみたいなのが表示されていますね、直しておいてください。

2019-05-15 06:32 UTC, shunji-yamaguchi commented on src/sho11/RectangleTest.java
> +public class RectangleTest {
@kenta-yamazaki 
👍 
特に理由がなければ、コードはコメントアウトしなくてよいですよ。
ローカル変数名の修正が大変であればこのままでもよいです。

2019-05-16 01:15 UTC, kenta-yamazaki commented on src/sho11/Rectangle21.java
> +            return true;
@hironoriohashi
修正しました。

2019-05-16 01:16 UTC, kenta-yamazaki commented on src/sho11/Rectangle23.java
> +        this.height = height;
三項演算子を使用して修正しました。

2019-05-16 01:16 UTC, kenta-yamazaki commented on src/sho11/Rectangle24.java
> +        int ey = Math.min(this.y + this.height, rectangle.y + rectangle.height);
変数名を修正しました。

2019-05-16 01:18 UTC, kenta-yamazaki commented on src/sho11/RectangleTest.java
> +        System.out.println("長方形の面積は、"+r.getArea()+"㎠です。");
@shunji-yamaguchi
僕のでは文字化けせずに表示されるみたいなのですが、、
`長方形の面積は、50㎠です。`

2019-05-16 01:19 UTC, kenta-yamazaki commented
@shunji-yamaguchi 
@hironoriohashi 
修正しました。再度レビューお願いします！

2019-05-17 03:11 UTC, hironoriohashi approved these changes
良いと思います

2019-05-20 00:17 UTC, shunji-yamaguchi commented on src/sho11/RectangleTest.java
> +        System.out.println("長方形の面積は、"+r.getArea()+"㎠です。");
@kenta-yamazaki 
エディタで開いたらちゃんと表示できました。
すいません、私の早とちりでした 🙇

2019-05-20 00:17 UTC, shunji-yamaguchi approved these changes
@kenta-yamazaki 
🆗 です。

2019-05-20 01:09 UTC, kenta-yamazaki commented
@shunji-yamaguchi 
@hironoriohashi 
ありがとうございます！

2019-05-20 01:09 UTC, merged