13章
kenta-yamazaki/java_lesson pull request #14
Opened 2019-05-17 04:31 UTC by kenta-yamazaki

@shunji-yamaguchi
@hironoriohashi
13章のプログラム作成しました。
レビューお願い致します！

2019-05-20 03:59 UTC, hironoriohashi commented on src/sho13/FactorialTest.java
> +    public static int factorial(int n) {
階乗を求める関数の引数に負の値を渡した場合、
例えば`factorial(-10)`とした場合でも戻り値は1で良いのでしょうか？

2019-05-20 08:27 UTC, kenta-yamazaki commented on src/sho13/FactorialTest.java
> +    public static int factorial(int n) {
@hironoriohashi
修正しました。

2019-05-20 08:28 UTC, kenta-yamazaki commented
@shunji-yamaguchi
@hironoriohashi 
修正しました。再度レビューお願いいたします！

2019-05-21 00:51 UTC, shunji-yamaguchi requested changes
@kenta-yamazaki 
レビューしました。ご確認をよろしくお願いします。

2019-05-21 00:51 UTC, shunji-yamaguchi commented on src/sho13/FactorialTest.java
> +        }
@kenta-yamazaki 
このメソッドならelseは書かなくても同じ処理を書けそうです。
elseなしのほうがコードがスッキリするかなと思うので修正してみてください。

さらにいうと三項演算子も使えそうですが、難しければ無理に使用しなくても良いです。

2019-05-21 00:51 UTC, shunji-yamaguchi commented on src/sho13/FactorialTest.java
> +            return 1;
@kenta-yamazaki 
補足ですが再帰関数（Javaでは再帰メソッド）は、「基底部」と呼ばれるこれ以上再起できない部分と、それ以外の「再帰」の部分に分かれます。
この場合、31行目が「基底部」ですね。

2019-05-21 00:51 UTC, shunji-yamaguchi commented on src/sho13/FactorialTest.java
> +            throw new Exception("負の値は指定できません。");
@kenta-yamazaki 
例外を投げる際は、呼び出し元で適切に回復できる場合はチェックされる例外、プログラミングエラーには実行時例外（チェックされない例外）を使用するのが良いです。（Effective Java という本の 項目70 に書いてありました。）

このメソッドの場合は実装者がコードを書いて呼び出すので、負の数が渡されるのはプログラミングエラーと見做して良いと思います。
なので実行時例外を投げるのが良いです。

また、例外を投げる際は適切な例外を選んで使用するべきです。
以下のサイトによく使用される実行時例外が紹介されていたので、参考にして修正してみてください。
https://chat-rate.com/it/3743/

2019-05-21 02:43 UTC, kenta-yamazaki commented on src/sho13/FactorialTest.java
> +        }
@shunji-yamaguchi
`   
 public static int factorial(int number) throws IllegalArgumentException {
        return number > 0 ? factorial(number - 1) : number == 0 ? 1 : throw new IllegalArgumentException("指定した値が正しくありません");
    }
`
三項演算子を使おうと思っているのですが、
この方法だと`Expected expression`という警告が出てしまいます。
髙宮さんが貼ったリンクのだとこれで正しいと思っているのですが・・

2019-05-21 05:12 UTC, kenta-yamazaki commented on src/sho13/FactorialTest.java
> +        }
@shunji-yamaguchi
修正しました

2019-05-21 05:12 UTC, kenta-yamazaki commented on src/sho13/FactorialTest.java
> +            throw new Exception("負の値は指定できません。");
@syunji-yamaguchi
修正しました

2019-05-21 05:13 UTC, kenta-yamazaki commented
@shunji-yamaguchi 
@hironoriohashi 
修正しました。再度レビューお願いします！

2019-05-21 05:17 UTC, shunji-yamaguchi commented on src/sho13/FactorialTest.java
> +        }
@kenta-yamazaki 
先ほどの話ですが、📝として残しておきます。

Javaの三項演算子は条件式の評価に対応する式を実行して値を返すためのものです。
なのでvoid型のメソッドを実行したり、throwで例外を投げるなどの処理は書けません。

また三項演算子はそれによりコードが簡潔になるときに使用するのが良いです。
三項演算子が二重になったり、式が複雑な場合は、三項演算子を使える場面でもif文を使用するのが良いです。

2019-05-21 05:20 UTC, kenta-yamazaki commented on src/sho13/FactorialTest.java
> +        }
@shunji-yamaguchi
ありがとうございます🙇🏻‍♂️

2019-05-21 06:56 UTC, shunji-yamaguchi approved these changes
@kenta-yamazaki 
🆗 です。
１点コメントしました。
修正するかはお任せするので、マージしても良いです。

2019-05-21 06:56 UTC, shunji-yamaguchi commented on src/sho13/FactorialTest.java
> +    public static int factorial(int n) throws IllegalArgumentException {
@kenta-yamazaki 
間違いではないのですが、throws節はチェックされる例外（検査例外）が投げられた場合の例外処理を、メソッド呼び出し側に伝播するためのものです。
なのでチェックされない例外（実行時例外）の場合はなくても問題ありません。

修正前の`Exception`はチェックされる例外だったので、mainメソッドで例外処理を記述する場合はfactorialメソッドにthrows節が必要でした。
修正後の`IllegalArgumentException`はチェックされない例外なので、throws節は不要であり、さらにいうとmainメソッドでの例外処理がなくてもコンパイルエラーとなりません。

実装者に例外が投げられることを伝えたい場合は、ドキュメンテーションコメントでの記述がよくされると思います。
JavaDocだと`@throws`タグまたは`@exception`タグを使用して、投げられる例外とその説明を記述できます。
https://www.javadrive.jp/javadoc/tag/index9.html

2019-05-22 03:04 UTC, hironoriohashi approved these changes
良いと思います

2019-05-22 04:58 UTC, kenta-yamazaki commented on src/sho13/FactorialTest.java
> +    public static int factorial(int n) throws IllegalArgumentException {
@shunji-yamaguchi
修正しました。

2019-05-22 04:58 UTC, kenta-yamazaki commented
@shunji-yamaguchi 
@hironoriohashi 
修正しました。再度レビューお願いします！

2019-05-22 05:00 UTC, shunji-yamaguchi approved these changes
@kenta-yamazaki 
🆗 です 👍

2019-05-22 05:09 UTC, kenta-yamazaki commented
@shunji-yamaguchi 
@hironoriohashi 
ありがとうございます！

2019-05-22 05:09 UTC, merged