14章
kenta-yamazaki/java_lesson pull request #15
Opened 2019-05-20 01:08 UTC by kenta-yamazaki

@shunji-yamaguchi
@hironoriohashi
14章のプログラム作成しました。レビューお願いします！

2019-05-21 03:42 UTC, hironoriohashi approved these changes
良いと思います

2019-05-21 09:34 UTC, shunji-yamaguchi requested changes
@kenta-yamazaki 
レビューしました。ご確認をよろしくお願いします。

2019-05-21 09:34 UTC, shunji-yamaguchi commented on src/sho14/Beta.java
> +}
@kenta-yamazaki 
改行入れておきましょう。

2019-05-21 09:34 UTC, shunji-yamaguchi commented on src/sho14/Gamma.java
> +}
@kenta-yamazaki 
改行入れておきましょう。

2019-05-21 09:34 UTC, shunji-yamaguchi commented on src/sho14/MySoundPlayable.java
> +}
@kenta-yamazaki 
改行入れておきましょう。

2019-05-21 09:34 UTC, shunji-yamaguchi commented on src/sho14/IconInfo.java
> +interface IconInfo {
@kenta-yamazaki 
`publicなインタフェース`ではなさそうです。
（publicについては17章の内容のはずなので、分からなければこのままでも良いと思います。）

2019-05-22 05:06 UTC, kenta-yamazaki commented on src/sho14/Beta.java
> +}
@shunji-yamaguchi
修正しました。

2019-05-22 05:06 UTC, kenta-yamazaki commented on src/sho14/Gamma.java
> +}
@shunji-yamaguchi
修正しました。

2019-05-22 05:06 UTC, kenta-yamazaki commented on src/sho14/MySoundPlayable.java
> +}
@shunji-yamaguchi
修正しました。

2019-05-22 05:07 UTC, kenta-yamazaki commented on src/sho14/IconInfo.java
> +interface IconInfo {
@shunji-yamaguchi
修正しました

2019-05-22 05:07 UTC, kenta-yamazaki commented
@shunji-yamaguchi 
@hironoriohashi 
修正しました。再度レビューお願いいたします！

2019-05-22 05:08 UTC, shunji-yamaguchi approved these changes
@kenta-yamazaki 
🆗 です。

2019-05-27 00:21 UTC, kenta-yamazaki commented
@hironoriohashi 
@shunji-yamaguchi 
ありがとうございます！

2019-05-27 00:21 UTC, merged