15章
kenta-yamazaki/java_lesson pull request #16
Opened 2019-05-20 07:03 UTC by kenta-yamazaki

@shunji-yamaguchi
@hironoriohashi
15章のプログラム作成しました。
レビューお願いします。

僕も髙宮さんと同じ問題の２つの理由がわからないので、教えていただきです！

2019-05-20 08:30 UTC, shunji-yamaguchi commented
@kenta-yamazaki 

> ”ジマイマ”が表示されて”レベッカ”が表示されない理由と、”ルーシー”と”ティギー”が表示される理由

これらはクラスフィールドとインスタンスフィールドの違いにより出ている差ですね。

クラスフィールドはクラスごとに持つフィールドです。
そのためそのクラスが必要になったとき（ロードされたとき）に、初期化が行われます。
さらにプログラムが終了するまでいつでも`クラス名.クラスフィールド名`で参照できます。

インスタンスフィールドはインスタンスごとに持つフィールドです。
そのためインスタンスを生成したときに初期化され、`インスタンス.インスタンスフィールド名`のようにインスタンスを介することで参照できます。

> ”ジマイマ”が表示されて”レベッカ”が表示されない理由

今回のプログラムではまず`main`メソッドが実行されますが、`main`メソッドを実行するには`GcQuiz`クラスをロードして初期化する必要があります。
そのため`main`メソッド実行前にクラスフィールド`q`が初期化され、その結果`[ジマイマ]が生まれました。`と表示されます。

また`[レベッカ]が生まれました。`と表示されるのは、インスタンスフィールド`r`が初期化されたときです。
このプログラムでは`GcQuiz`クラスのインスタンスの生成は一度も行われていません。
なので`[レベッカ]が生まれました。`とは表示されません。

> ”ルーシー”と”ティギー”が表示される理由

`ClassA`クラスのクラスフィールド`last`が`new ClassB("ルーシー", new ClassA("ティギー"));`で生成したインスタンスを参照しているためです。

まず引数として必要なインスタンス`new ClassA("ティギー")`が生成され【以下、Aとする】、クラスフィールド`last`の参照先がインスタンスAとなります。
次にインスタンス`new ClassB("ルーシー", A);`が生成され【以下、Bとする】、クラスフィールド`last`の参照先がインスタンスBとなり、そのインスタンスフィールド`friend`はインスタンスAを参照する状態になります。

なので、`System.out.println("ClassA.last = " + ClassA.last);`ではルーシーとティギーを表示することができます。

2019-05-21 01:21 UTC, kenta-yamazaki commented
@shunji-yamaguchi 
ありがとうございます。
青木さんの助けもあり、無事理解できた気がします！

2019-05-21 03:44 UTC, hironoriohashi approved these changes
良いと思います

2019-05-21 09:56 UTC, shunji-yamaguchi requested changes
@kenta-yamazaki 
レビューしました。ご確認をよろしくお願いします。

2019-05-21 09:56 UTC, shunji-yamaguchi commented on src/sho15/GcQuiz.java
> +}
@kenta-yamazaki 
改行入れておきましょう。

2019-05-22 05:10 UTC, kenta-yamazaki commented on src/sho15/GcQuiz.java
> +}
@shunji-yamaguchi
修正しました。

2019-05-22 05:11 UTC, kenta-yamazaki commented
@shunji-yamaguchi 
@hironoriohashi 
修正しました。再度レビューお願いいたします！

2019-05-22 05:12 UTC, shunji-yamaguchi approved these changes
@kenta-yamazaki 
🆗 です。

2019-05-22 05:13 UTC, kenta-yamazaki commented
@shunji-yamaguchi 
@hironoriohashi 
ありがとうございます。

2019-05-22 05:13 UTC, merged