16章
kenta-yamazaki/java_lesson pull request #17
Opened 2019-05-27 02:26 UTC by kenta-yamazaki

@shunji-yamaguchi
@hironoriohashi
16章のプログラム作成しました。レビューお願いいたします！

2019-05-27 09:52 UTC, hironoriohashi approved these changes
良いと思います

2019-05-27 10:50 UTC, shunji-yamaguchi requested changes
@kenta-yamazaki 
レビューしました。ご確認をよろしくお願いします。

2019-05-27 10:50 UTC, shunji-yamaguchi commented on src/sho16/Runner.java
> +        stopRunning();
@kenta-yamazaki 
サンプルコードに実行のための処理を追加で書けているのはとても良いです 👍 
しかし、ここでスレッドを終了させるためのメソッド`stopRunning()`を呼び出すと、自分で自分のスレッドを終了することになります。
自身以外のスレッドが終了する形に修正してみてください。

2019-05-27 10:50 UTC, shunji-yamaguchi commented on src/sho16/Periodic.java
> +                Thread.sleep(time);
@kenta-yamazaki 
余談ですが、`i`秒スリープしたい場合は`TimeUnit`を使用して、`TimeUnit.SECONDS.sleep(i);`と書くこともできるそうです。
ミリ秒に直す計算が不要なので便利ですね。

2019-05-28 01:48 UTC, kenta-yamazaki commented on src/sho16/Runner.java
> +        stopRunning();
@shunji-yamaguchi
修正しました。

2019-05-28 01:48 UTC, kenta-yamazaki commented on src/sho16/Periodic.java
> +                Thread.sleep(time);
@shunji-yamaguchi
修正しました。

2019-05-28 01:49 UTC, kenta-yamazaki commented
@shunji-yamaguchi 
@hironoriohashi 
修正しました。再度レビューお願い致します！

2019-05-28 05:08 UTC, shunji-yamaguchi requested changes
@kenta-yamazaki 
レビューしました。ご確認をよろしくお願いします。

2019-05-28 05:08 UTC, shunji-yamaguchi commented on src/sho16/Runner.java
> +        new Runner2().start();
@kenta-yamazaki 
自身以外のスレッドから終了する形に直せています 🙆‍♂ 

ですがスレッドを停止させるためのフラグフィールド`running`をクラスフィールドにするのは違和感があります。
`Runner`クラスのインスタンスを複数生成して、それらからスレッドを複数生成した場合、一度の`stopRunning()`ですべてのスレッドが停止してしまうので。
異なるスレッドは停止しないよう、`running`をインスタンスフィールドを修正してみて欲しいです。

また`new Runner2().start();`でスレッドを停止させるためのスレッドを生成していますが、スレッドの停止はmainメソッドに記述してくれても良いです。
mainメソッドを実行しているのもスレッドなので（mainメソッドで`Thread.currentThread().getName()`を実行すると文字列`main` が取得できます。なので`main`という名前のスレッドにより、mainメソッドが実行されているのが分かります。）

2019-05-29 01:25 UTC, kenta-yamazaki commented on src/sho16/Runner.java
> +        new Runner2().start();
@shunji-yamaguchi
ありがとうございます！修正しました。

2019-05-29 01:26 UTC, shunji-yamaguchi approved these changes
@kenta-yamazaki 
🆗 です 👍

2019-05-29 01:56 UTC, kenta-yamazaki commented
@shunji-yamaguchi 
@hironoriohashi 
ありがとうございます！

2019-05-29 01:56 UTC, merged