18章
kenta-yamazaki/java_lesson pull request #19
Opened 2019-05-29 06:50 UTC by kenta-yamazaki

@shunji-yamaguchi
@hironoriohashi
18章のプログラム作成しました。レビューお願い致します！

2019-05-30 06:40 UTC, shunji-yamaguchi requested changes
@kenta-yamazaki 
レビューしました。ご確認をよろしくお願いします。

2019-05-30 06:40 UTC, shunji-yamaguchi commented on src/sho18/ShowFile1.java
> +        try (BufferedReader reader = new BufferedReader(new FileReader(fileName))) {
👍

2019-05-30 06:40 UTC, shunji-yamaguchi commented on src/sho18/WriteFile1.java
> +        try (BufferedReader reader = new BufferedReader(new InputStreamReader(System.in)); PrintWriter writer = new PrintWriter(new BufferedWriter(new FileWriter(fileName)))) {
@kenta-yamazaki 
変数宣言を１行で２回するのは良くないです。
改行しておきましょう。

2019-05-30 06:40 UTC, shunji-yamaguchi commented on src/sho18/WriteFile1.java
> +import java.io.*;
@kenta-yamazaki 
ワイルドカードインポートは使わないようにしましょう。

2019-05-30 06:40 UTC, shunji-yamaguchi commented on src/sho18/FileDump1.java
> +import java.io.*;
@kenta-yamazaki 
ワイルドカードインポートは使用しないようにしましょう。

2019-05-30 06:40 UTC, shunji-yamaguchi commented on src/sho18/FileDump1.java
> +        }
@kenta-yamazaki 
このif文による処理ですが、`String.format()`を使用するとif文なしで書くことができます。
`String.format()`を使用して書いてみてください 🙏

2019-05-30 06:40 UTC, shunji-yamaguchi commented on src/sho18/FindFile1.java
> +            while ((line = reader.readLine()) != null) {
@kenta-yamazaki 
`lineNumber`の処理は、for文を使用して書くこともできそうです。
while文でなくfor文を使用する形に直してみてください 🙏

2019-05-30 06:40 UTC, shunji-yamaguchi commented on src/sho18/Prime1.java
> +    static final int MAX_PRIME = 1000;
@kenta-yamazaki 
この定数はこのクラスでしか使用しないものですね。
変数のスコープは最小にしておくのが良いので、`private`にしておきましょう。

2019-05-30 06:40 UTC, shunji-yamaguchi commented on src/sho18/Prime1.java
> +    public static void writerPrime(PrintWriter writer) {
@kenta-yamazaki 
このメソッドはこのクラスからのみ呼び出されるメソッドですね。
外部のクラスに公開する必要性はないので、`private`にしておきましょう。

2019-05-31 01:28 UTC, kenta-yamazaki commented on src/sho18/WriteFile1.java
> +        try (BufferedReader reader = new BufferedReader(new InputStreamReader(System.in)); PrintWriter writer = new PrintWriter(new BufferedWriter(new FileWriter(fileName)))) {
@shunji-yamaguchi
修正しました。

2019-05-31 01:28 UTC, kenta-yamazaki commented on src/sho18/WriteFile1.java
> +import java.io.*;
@shunji-yamaguchi
修正しました。

2019-05-31 01:28 UTC, kenta-yamazaki commented on src/sho18/FileDump1.java
> +import java.io.*;
@shunji-yamaguchi
修正しました。

2019-05-31 01:28 UTC, kenta-yamazaki commented on src/sho18/FileDump1.java
> +        }
@shunji-yamaguchi
修正しました。

2019-05-31 01:28 UTC, kenta-yamazaki commented on src/sho18/FindFile1.java
> +            while ((line = reader.readLine()) != null) {
@shunji-yamaguchi
修正しました。

2019-05-31 01:28 UTC, kenta-yamazaki commented on src/sho18/Prime1.java
> +    static final int MAX_PRIME = 1000;
@shunji-yamaguchi
修正しました。

2019-05-31 01:29 UTC, kenta-yamazaki commented on src/sho18/Prime1.java
> +    public static void writerPrime(PrintWriter writer) {
@shunji-yamaguchi
修正しました。

2019-05-31 01:29 UTC, kenta-yamazaki commented
@shunji-yamaguchi 
@hironoriohashi
修正しました。再度レビューお願いいたします！

2019-05-31 01:43 UTC, shunji-yamaguchi approved these changes
@kenta-yamazaki 
🆗 です 🎉

2019-05-31 01:43 UTC, shunji-yamaguchi commented on src/sho18/WriteFile1.java
> +             PrintWriter writer = new PrintWriter(new BufferedWriter(new FileWriter(fileName)))) {
@kenta-yamazaki 
余談ですが
```java
try (BufferedReader reader = new BufferedReader(new InputStreamReader(System.in));
        PrintWriter writer = new PrintWriter(new BufferedWriter(new FileWriter(fileName)))) {
    String line;
```
```java
try (
    BufferedReader reader = new BufferedReader(new InputStreamReader(System.in));
    PrintWriter writer = new PrintWriter(new BufferedWriter(new FileWriter(fileName)))
) {
    String line;
```
みたいな書き方も良く見ます。
自分が見やすいと感じる書き方を使用してくれれば良いです 👍

2019-05-31 04:41 UTC, shunji-yamaguchi reviewed
補足を追加しました。

2019-05-31 04:41 UTC, shunji-yamaguchi commented on src/sho18/WriteFile1.java
> +        try (BufferedReader reader = new BufferedReader(new InputStreamReader(System.in));
@kenta-yamazaki 
補足です。
closeメソッドについてですが、基本的に内部のラップされたストリームも自動でcloseされます。
なのでこの場合`reader.close()`を実行すると`new InputStreamReader`と`System.in`についてもcloseが実行されます。
通常のストリームなら必要なときにまたインスタンスを生成すれば良いですが、`System.in`についてはSystemクラスのクラスフィールドなので、一度closeしてしまうと再度使用することはできません。
`System.in`を使用する際は注意が必要です。

2019-06-04 05:05 UTC, kenta-yamazaki commented
@shunji-yamaguchi 
@hironoriohashi
ありがとうございます！

2019-06-04 05:05 UTC, merged