1章
kenta-yamazaki/java_lesson pull request #2
Opened 2019-04-22 08:41 UTC by kenta-yamazaki

レビューお願いいたします！

2019-04-22 09:26 UTC, shunji-yamaguchi requested changes
@kenta-yamazaki 
レビューしました。ご確認をよろしくお願いします。

2019-04-22 09:26 UTC, shunji-yamaguchi commented on src/sho1/Aisatsu2.java
> +public class Aisatsu2 {
@kenta-yamazaki 
実装が漏れていますね。実装お願いします。

2019-04-22 09:26 UTC, shunji-yamaguchi commented on src/sho1/Kantan.java
> +public class Kantan{
@kenta-yamazaki 
中括弧の前は半角スペースをお願いします。

2019-04-23 00:22 UTC, kenta-yamazaki commented on src/sho1/Aisatsu2.java
> +public class Aisatsu2 {
すみません。おそらく保存前のファイルをaddしていました。修正しました。

2019-04-23 00:22 UTC, kenta-yamazaki commented on src/sho1/Kantan.java
> +public class Kantan{
修正しました。

2019-04-23 00:26 UTC, kenta-yamazaki commented
@shunji-yamaguchi 
@hironoriohashi
修正しました。再度レビューお願いします！！

2019-04-23 00:35 UTC, shunji-yamaguchi approved these changes
@kenta-yamazaki 
🆗 です。

2019-04-23 03:17 UTC, hironoriohashi approved these changes
良いと思います

2019-04-23 04:10 UTC, kenta-yamazaki commented
ありがとうございます。

2019-04-23 04:13 UTC, merged