4章
kenta-yamazaki/java_lesson pull request #5
Opened 2019-04-24 05:14 UTC by kenta-yamazaki

@hironoriohashi
@shunji-yamaguchi
4章プログラム作成しました。
レビューお願いします！

2019-04-24 06:08 UTC, shunji-yamaguchi requested changes
@kenta-yamazaki 
レビューしました。ご確認をよろしくお願いします。

2019-04-24 06:08 UTC, shunji-yamaguchi commented on src/sho4/Jikoku.java
> +                System.out.println("時刻は0～23の間ですよ。");
@kenta-yamazaki 
これは「時刻の範囲を超えています」と表示すべきそれ以外のパターンですね。修正をお願いします。

2019-04-24 06:08 UTC, shunji-yamaguchi commented on src/sho4/Jikoku.java
> +            int time_now = Integer.parseInt(line);
@kenta-yamazaki 
Java言語ではメソッド名と変数名はキャメルケースでの記述が一般的です。
お手数ですが修正お願いします（他クラスについても同様に）。

2019-04-24 06:08 UTC, shunji-yamaguchi commented on src/sho4/Jikoku.java
> +            } else if (0 <= time_now && time_now < 12) {
@kenta-yamazaki 
不等号の向き、条件式の順番が読みやすくて良いですね 👍 
等号付き不等号で統一すると、時刻の範囲が一目で分かるのでより分かりやすいかなと思いました。（修正するかはお任せします。）

2019-04-24 06:08 UTC, shunji-yamaguchi commented on src/sho4/Kasa1.java
> +            int rainy_per = Integer.parseInt(line);
@kenta-yamazaki 
問題文から推測するに`per`は`percent`の略ですかね？
変数名は分かりやすさが大切なので省略するのはあまりよくありません。
修正をお願いします（他のクラスについても同様に）。

2019-04-24 07:05 UTC, kenta-yamazaki commented on src/sho4/Jikoku.java
> +                System.out.println("時刻は0～23の間ですよ。");
21、22行目はelseで似たような処理をしていたので削除しました。

2019-04-24 07:06 UTC, kenta-yamazaki commented on src/sho4/Jikoku.java
> +            int time_now = Integer.parseInt(line);
キャメルケースに修正しました。

2019-04-24 07:06 UTC, kenta-yamazaki commented on src/sho4/Jikoku.java
> +            } else if (0 <= time_now && time_now < 12) {
等号付き不等号で統一しました。

2019-04-24 07:07 UTC, kenta-yamazaki commented on src/sho4/Kasa1.java
> +            int rainy_per = Integer.parseInt(line);
変数名をrainyPercentに修正しました。

2019-04-24 07:07 UTC, kenta-yamazaki commented
@shunji-yamaguchi 
@hironoriohashi
修正しました。
再度レビューお願いします！！

2019-04-24 07:17 UTC, shunji-yamaguchi requested changes
@kenta-yamazaki 
レビューしました。ご確認をよろしくお願いします。

2019-04-24 07:17 UTC, shunji-yamaguchi commented on src/sho4/Kasa2.java
> +            int rainy_per = Integer.parseInt(line);
@kenta-yamazaki 
`Kasa2.java`と`Kasa3.java`についても変数名のキャメルケース化をお願いします。

2019-04-24 07:17 UTC, shunji-yamaguchi commented on src/sho4/Jikoku.java
> +import java.io.*;
@kenta-yamazaki 
せっかくなのでこのプルリクエストからワイルドカードなしのインポート文に修正してみてください。

2019-04-24 07:33 UTC, kenta-yamazaki commented on src/sho4/Kasa2.java
> +            int rainy_per = Integer.parseInt(line);
キャメルケースに修正しました。

2019-04-24 07:34 UTC, kenta-yamazaki commented on src/sho4/Jikoku.java
> +import java.io.*;
ワイルドカードなしのインポート文に修正しました。

2019-04-24 07:35 UTC, kenta-yamazaki commented
@shunji-yamaguchi 
@hironoriohashi
修正しました。
再度レビューお願いします！

2019-04-24 07:52 UTC, shunji-yamaguchi approved these changes
@kenta-yamazaki 
レビューしました。ご確認をよろしくお願いします。

2019-04-24 07:52 UTC, shunji-yamaguchi commented on src/sho4/Jikoku.java
> +import java.io.*;
@kenta-yamazaki 
`Jikoku.java` `Kasa1` のワイルドカードインポート修正が漏れているので、修正お願いします。

2019-04-24 08:00 UTC, kenta-yamazaki commented
@shunji-yamaguchi 
@hironoriohashi
修正しました。
再度レビューお願いします！

2019-04-24 08:01 UTC, shunji-yamaguchi approved these changes
@kenta-yamazaki 
🆗 です。

2019-04-24 12:23 UTC, hironoriohashi approved these changes
良いと思います。

2019-04-25 00:13 UTC, kenta-yamazaki commented
@shunji-yamaguchi 
@hironoriohashi 
忙しい中のレビューありがとうございます:bow:

2019-04-25 00:13 UTC, merged