5章
kenta-yamazaki/java_lesson pull request #6
Opened 2019-04-25 05:01 UTC by kenta-yamazaki

@shunji-yamaguchi
@hironoriohashi
5章のプログラム作成しました。
レビューお願いします！！

2019-04-25 06:00 UTC, shunji-yamaguchi requested changes
@kenta-yamazaki 
レビューしました。ご確認をよろしくお願いします。

2019-04-25 06:00 UTC, shunji-yamaguchi commented on src/sho5/Drink6.java
> + *<pre>{@code
👍

2019-04-25 06:00 UTC, shunji-yamaguchi commented on src/sho5/Drink6.java
> +        } catch (NumberFormatException e) {
@kenta-yamazaki 
ここでNumberFormatExceptionをcatchしていますが、不要な処理です。削除しておいてください。

どういうときに必要なのかは下巻13章で学習する内容なので、無理に理解しなくても大丈夫です。
気になれば下巻13章p86にNumberFormatExceptionについて記述があるので読んでみてもよいですよ。

2019-04-25 06:00 UTC, shunji-yamaguchi commented on src/sho5/Drink7.java
> +}
@kenta-yamazaki 
改行がないですね 👀

2019-04-25 06:00 UTC, shunji-yamaguchi commented on src/sho5/Drink2.java
> +public class Drink2 {
@kenta-yamazaki 
せっかくなのでp125問題5-8のエラーを解決できるようなプログラムも作成してみてください。
このクラスを直接修正していただいても良いです。

2019-04-25 07:26 UTC, kenta-yamazaki commented on src/sho5/Drink2.java
> +public class Drink2 {
問題5-8のプログラムを新しく作成しました。

2019-04-25 07:27 UTC, kenta-yamazaki commented on src/sho5/Drink7.java
> +}
末尾に改行追加しました。

2019-04-25 07:27 UTC, kenta-yamazaki commented on src/sho5/Drink6.java
> +        } catch (NumberFormatException e) {
不要な例外処理を削除しました。

2019-04-25 07:27 UTC, kenta-yamazaki commented
@shunji-yamaguchi 
@hironoriohashi
修正しました。
再度レビューお願いします！

2019-04-25 15:15 UTC, hironoriohashi commented on src/sho5/Drink.java
> +            int number = Integer.parseInt(line);
変数名が`number`や`moji`では抽象的なので、
変数に格納されている値がユーザの選択だと分かるような変数名にしてみてください。

2019-04-26 00:02 UTC, kenta-yamazaki commented on src/sho5/Drink.java
> +            int number = Integer.parseInt(line);
selectNumber、selectMojiなどの変数は妥当ですか？

2019-04-26 00:04 UTC, shunji-yamaguchi approved these changes
@kenta-yamazaki 
🆗 です。

2019-04-26 00:21 UTC, hironoriohashi commented on src/sho5/Drink.java
> +            int number = Integer.parseInt(line);
もう一息です。
`selectNumber`、`selectMoji`ではユーザの選択だと一目では分からないかもしれません。
`リーダブルコード`という本があるので、
もし、読んだことが無ければ一度読んでみても良いかもしれません。
ITSが管理している書籍の中にあります。
下記のURLからITSの書籍管理のページに移れます。
[ITS書籍管理のURL](https://script.google.com/a/esm.co.jp/macros/s/AKfycbyFv5CxNimZjZ_iUitJazRG1WOSAixJe2jcmYXFFQ4b_KjyyWw/exec)

2019-04-26 01:28 UTC, kenta-yamazaki commented on src/sho5/Drink.java
> +            int number = Integer.parseInt(line);
ありがとうございます！
指摘を踏まえて、`userSelectNumber`という変数にしようと思います。

2019-04-26 02:07 UTC, kenta-yamazaki commented
@shunji-yamaguchi 
@hironoriohashi 
変数名を修正しました。
再度レビューお願いします。

2019-04-26 03:33 UTC, hironoriohashi approved these changes
良いと思います

2019-05-07 08:45 UTC, merged