6章
kenta-yamazaki/java_lesson pull request #7
Opened 2019-04-25 06:33 UTC by kenta-yamazaki

@shunji-yamaguchi
@hironoriohashi
6章のプログラム作成しました。
レビューお願いします！！

2019-04-25 06:57 UTC, shunji-yamaguchi requested changes
@kenta-yamazaki 
レビューしました。ご確認をよろしくお願いします。

2019-04-25 06:57 UTC, shunji-yamaguchi commented on src/sho6/Count2.java
> +        for (int number = 1; number < 3; number++) {
@kenta-yamazaki 
表示されない数字がありそうです。

2019-04-25 06:57 UTC, shunji-yamaguchi commented on src/sho6/Count3.java
> +            System.out.println("3乗は" + (number * number * number) + "です。");
@kenta-yamazaki 
累乗の計算は[Math.pow](https://docs.oracle.com/javase/jp/8/docs/api/java/lang/Math.html#pow-double-double-) を使って書くこともできます。

2019-04-25 06:57 UTC, shunji-yamaguchi commented on src/sho6/DrawGraph1.java
> +            for (int number2 = 0; number2 < number1; number2++) {
@kenta-yamazaki 
こんなやりとりがありました 🙏 ご参考に
https://idobata.io/archives/messages/30593712#message_30593712

2019-04-26 01:51 UTC, kenta-yamazaki commented on src/sho6/Count2.java
> +        for (int number = 1; number < 3; number++) {
正しく表示されるように修正しました。

2019-04-26 01:53 UTC, kenta-yamazaki commented on src/sho6/Count3.java
> +            System.out.println("3乗は" + (number * number * number) + "です。");
Math.powを使い書き直しました。

2019-04-26 01:54 UTC, kenta-yamazaki commented on src/sho6/DrawGraph1.java
> +            for (int number2 = 0; number2 < number1; number2++) {
ありがとうございます。
変数i、j、k…を使って修正しました。

2019-04-26 01:55 UTC, kenta-yamazaki commented
@shunji-yamaguchi 
@hironoriohashi
修正しました。
再度レビューお願いいたします！

2019-04-26 03:35 UTC, hironoriohashi approved these changes
良いと思います

2019-04-26 04:08 UTC, shunji-yamaguchi approved these changes
@kenta-yamazaki 
🆗 です。

2019-04-26 04:58 UTC, shunji-yamaguchi requested changes
@kenta-yamazaki 
指摘を追加しました。ご確認をよろしくお願いします。

2019-04-26 04:58 UTC, shunji-yamaguchi commented on src/sho6/Count3.java
> +            System.out.println("3乗は" + Math.pow(i, 3) + "です。");
@kenta-yamazaki 
すいません。 🆗 としましたが、追加で指摘します。

こちら実際に実行してみると、教本の`Count3.java`の実行結果とは異なる部分がありませんか？
修正してみてください。

2019-04-26 06:02 UTC, kenta-yamazaki commented on src/sho6/Count3.java
> +            System.out.println("3乗は" + Math.pow(i, 3) + "です。");
おそらく実行結果が異なる部分は、`端数が余計についていること`、だと思うのですけれども
`(int)Math.pow(i, 2)`というコードに修正してもいいですか？

2019-04-26 06:07 UTC, shunji-yamaguchi commented on src/sho6/Count3.java
> +            System.out.println("3乗は" + Math.pow(i, 3) + "です。");
@kenta-yamazaki 
はい、私もその認識での指摘でした 👍

2019-04-26 06:08 UTC, kenta-yamazaki commented on src/sho6/Count3.java
> +            System.out.println("3乗は" + Math.pow(i, 3) + "です。");
@shunji-yamaguchi
了解です。ありがとうございます！

2019-04-26 06:18 UTC, kenta-yamazaki commented on src/sho6/Count3.java
> +            System.out.println("3乗は" + Math.pow(i, 3) + "です。");
修正しました。

2019-04-26 06:19 UTC, kenta-yamazaki commented
@hironoriohashi 
@shunji-yamaguchi 
修正しました。
再度レビューお願いします。

2019-04-26 07:22 UTC, shunji-yamaguchi approved these changes
@kenta-yamazaki 
🆗 です。

2019-04-26 13:31 UTC, hironoriohashi approved these changes
良いと思います

2019-05-07 08:54 UTC, kenta-yamazaki commented
@shunji-yamaguchi 
@hironoriohashi 
ありがとうございます！

2019-05-07 08:54 UTC, merged