7章
kenta-yamazaki/java_lesson pull request #8
Opened 2019-05-07 07:51 UTC by kenta-yamazaki

@shunji-yamaguchi
@hironoriohashi
7章作成しました。
レビューお願いします！

2019-05-08 00:58 UTC, shunji-yamaguchi requested changes
@kenta-yamazaki 
レビューしました。ご確認をよろしくお願いします。

2019-05-08 00:58 UTC, shunji-yamaguchi commented on src/sho7/CopyLowet.java
> +public class CopyLowet {
@kenta-yamazaki 
`Lowet` スぺスミスですかね？

2019-05-08 00:58 UTC, shunji-yamaguchi commented on src/sho7/Graph1.java
> +            System.out.println("");
@kenta-yamazaki 
すいません、これまで指摘が漏れてましたが、改行コードのみ出力したい場合は引数なしで `System.out.println();` と書くこともできます。
上巻p168で解説されているオーバーロードというやつです。
https://docs.oracle.com/javase/jp/8/docs/api/java/io/PrintStream.html#println--

2019-05-08 06:15 UTC, kenta-yamazaki commented on src/sho7/CopyLowet.java
> +public class CopyLowet {
@shunji-yamaguchi
すみません。スペルミスでした。
修正しました。

2019-05-08 06:15 UTC, kenta-yamazaki commented on src/sho7/Graph1.java
> +            System.out.println("");
@shunji-yamaguchi
修正しました。

2019-05-08 06:16 UTC, kenta-yamazaki commented
@shunji-yamaguchi 
@hironoriohashi
修正しました。
再度レビューお願いします！！

2019-05-08 06:21 UTC, hironoriohashi commented on src/sho7/CopyLowet.java
> +public class CopyLowet {
`CopyLower.java`に修正したなら、`CopyLowet.java`は不要ではないでしょうか？

2019-05-08 06:53 UTC, hironoriohashi reviewed
良いと思います

2019-05-08 06:54 UTC, kenta-yamazaki commented on src/sho7/CopyLowet.java
> +public class CopyLowet {
@hironoriohashi
CopyLowet.javaを削除しました。

2019-05-09 00:22 UTC, shunji-yamaguchi requested changes
@kenta-yamazaki 
指摘を１点追加したのでご確認をよろしくお願いします 🙏

2019-05-09 00:22 UTC, shunji-yamaguchi commented on src/sho7/hello.txt
> +���͎R���Ƃ����܂��B�ǂ�����낵���B
@kenta-yamazaki 
こちら文字コードがSheft-JISになっていますが、`MakeHtml`は文字化けせずに実行できていますか？
intellijのエンコードの設定をutf-8にしたのなら、文字化けするのでは？と思ったので

2019-05-09 02:28 UTC, kenta-yamazaki commented on src/sho7/hello.txt
> +���͎R���Ƃ����܂��B�ǂ�����낵���B
@shunji-yamaguchi
エディタでhello.txtをutf-8にして保存したところ、文字化けせずに表示されました！

2019-05-09 04:02 UTC, shunji-yamaguchi commented on src/sho7/hello.txt
> +���͎R���Ƃ����܂��B�ǂ�����낵���B
@kenta-yamazaki 
👍 
hello.txtのutf-8への修正もコミットしてプッシュお願いします。

2019-05-09 04:30 UTC, kenta-yamazaki commented on src/sho7/hello.txt
> +���͎R���Ƃ����܂��B�ǂ�����낵���B
@shunji-yamaguchi
修正しました。

2019-05-09 04:31 UTC, kenta-yamazaki commented
@shunji-yamaguchi 
@hironoriohashi 
修正しました。再度レビューお願いします。

2019-05-09 05:57 UTC, shunji-yamaguchi approved these changes
@kenta-yamazaki 
🆗 です。

2019-05-09 06:33 UTC, kenta-yamazaki commented
@shunji-yamaguchi 
@hironoriohashi 
ありがとうございます！

2019-05-09 06:34 UTC, merged